version: 2

builds:
  - main: ./cmd/ghaw
    binary: ghaw
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: dzoba
      name: homebrew-tap
    homepage: https://github.com/dzoba/github-actions-watcher
    description: Terminal TUI for monitoring GitHub Actions workflow runs
    license: MIT
    install: |
      bin.install "ghaw"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
